### ISSUE TITLE
User Story: Download Results

### ISSUE THREAD

**Issue by oankit** [UBCO-COSC499-Summer-2024/team-1-capstone-gradefalcon#18]
- As an instructor, I want to download results so that I can analyze and record exam data.

**Tasks:**
- [x] Implement Result Download Feature
- [x] Integrate Download with Instructor pages
- [x] Download results for class
- [x] Download results for exam
