### ISSUE TITLE
User Story: Create and Manage Classes

### ISSUE THREAD

**Issue by oankit** [UBCO-COSC499-Summer-2024/team-1-capstone-gradefalcon#21]
- As an instructor, I want to create and manage classes so that I can organize students and exams.

   **Tasks:**
   - [x] [Design Database Schema for Classes](#5)
   - [x] [Implement Class Management Interface](#7)
   - [x] #82
   - [x] #54 
   - [ ] [Test Class Creation and Management Features](#8)
