### ISSUE TITLE
User Story: Create and Manage Exams

### ISSUE THREAD

**Issue by oankit** [UBCO-COSC499-Summer-2024/team-1-capstone-gradefalcon#22]
- As an instructor, I want to create and manage exams so that I can set up tests for my students.

   **Tasks:**
   - [x] [Design Database Schema for Exams](#9)
   - [x] [Implement Exam Creation Functionality](#10)
   - [x] [Implement Exam Management Interface](#11)
   - [x] [Test Exam Creation and Management Features](#12)
   - [x] #107
